// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVgSwX8FBnDA7eF0hRnTFJWOFJfpbLzGU',
    appId: '1:850276970590:web:402a701b854477858e04cf',
    messagingSenderId: '850276970590',
    projectId: 'digital-twin-a0e51',
    authDomain: 'digital-twin-a0e51.firebaseapp.com',
    storageBucket: 'digital-twin-a0e51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7aivjSGG4kuhzYRcHFVJIqmS_kV-ua0',
    appId: '1:850276970590:android:e40af799f4a536bc8e04cf',
    messagingSenderId: '850276970590',
    projectId: 'digital-twin-a0e51',
    storageBucket: 'digital-twin-a0e51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQSOaj0fSzkSQzSULDXTBdKapy7QeyDGQ',
    appId: '1:850276970590:ios:1efa38922d4462148e04cf',
    messagingSenderId: '850276970590',
    projectId: 'digital-twin-a0e51',
    storageBucket: 'digital-twin-a0e51.firebasestorage.app',
    iosBundleId: 'com.example.intersectionIntelligence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQSOaj0fSzkSQzSULDXTBdKapy7QeyDGQ',
    appId: '1:850276970590:ios:1efa38922d4462148e04cf',
    messagingSenderId: '850276970590',
    projectId: 'digital-twin-a0e51',
    storageBucket: 'digital-twin-a0e51.firebasestorage.app',
    iosBundleId: 'com.example.intersectionIntelligence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVgSwX8FBnDA7eF0hRnTFJWOFJfpbLzGU',
    appId: '1:850276970590:web:402a701b854477858e04cf',
    messagingSenderId: '850276970590',
    projectId: 'digital-twin-a0e51',
    authDomain: 'digital-twin-a0e51.firebaseapp.com',
    storageBucket: 'digital-twin-a0e51.firebasestorage.app',
  );
}
