name: digital_twin_step_2_live_sync
description: "Step 2 – Real-time live sync of Digital Twin markers via Firestore."
version: 2.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0

  provider: ^6.1.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
