name: digital_twin_step_5_intelligent_twin
description: "Step 5 - Intelligent Twin: two-object interception and automatic meeting point."
version: 5.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1

  # OpenStreetMap - no API key needed
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # State management
  provider: ^6.1.2

  # Date/time formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
